### ISSUE TITLE
No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by r0bj** [ahmetb/kubectl-pods_on#1]
I encountered an issue while using the kubectl-pods_on plugin, where it fails with the following error message:
```
F1021 19:11:43.839135    3675 main.go:104] failed to create clientset: no Auth Provider found for name "oidc"
```

kubeconfig user:
```
- name: <email>
  user:
    auth-provider:
      config:
        client-id: <client-id>
        client-secret: <client-secret>
        id-token: <id-token>
        idp-issuer-url: <idp-issuer-url>
        refresh-token: <refresh-token>
      name: oidc
```

It seems the plugin is unable to recognize the oidc authentication provider. This configuration works correctly with kubectl and other plugins, but fails with this one.

Plugin version: v0.1.0
